# ── Локальная разработка ──────────────────────────────────────

listener 1883 0.0.0.0
protocol mqtt

listener 9001 0.0.0.0
protocol websockets

plugin /usr/lib/mosquitto_dynamic_security.so
plugin_opt_config_file /mosquitto/config/dynsec.json

persistence true
persistence_location /mosquitto/data/

log_dest stdout
log_type all

allow_anonymous false